#pragma once

#define MAX_BOOKS_AMOUNT 30
#define MAX_BOOK_TITLE_LENGTH 256
#define MAX_BOOK_AUTHORS_AMOUNT 32
#define MAX_BOOK_ANNOTATION_LENGTH 512
#define MAX_BOOK_AUTHOR_NAME_LENGTH 32
#define MAX_BOOK_TAGS_AMOUNT 16
#define MAX_BOOK_TAG_LENGTH 32
#define MAX_ONE_BOOK_AMOUNT 10